# tests.cmake - Modular test integration for HumbleEngine

# Only include tests if explicitly requested
if(HUMBLEENGINE_BUILD_TESTS)
    include(CTest)
    enable_testing()
    find_package(Catch2 CONFIG QUIET)
    if(TARGET Catch2::Catch2WithMain AND EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_engine.cpp")
        add_executable(tests_engine tests/test_engine.cpp)
        target_link_libraries(tests_engine PRIVATE Catch2::Catch2WithMain ${PROJECT_NAME})
        target_compile_features(tests_engine PRIVATE cxx_std_23)
        add_test(NAME engine_tests COMMAND tests_engine)
        if(TARGET Catch2::Catch2)
            include(Catch)
            catch_discover_tests(tests_engine)
        endif()
    else()
        message(STATUS "Catch2 target missing – skipping tests.")
    endif()
endif()
