name: Build and Test

on:
  push:
    branches: [ main, ver1 ]
  pull_request:
    branches: [ main, ver1 ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }} - ${{ matrix.build_type }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC-13 and dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13 ninja-build ccache \
            xorg-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxrandr-dev \
            libxinerama-dev libxcursor-dev libxi-dev libasound2-dev pkg-config
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
          echo "CC=gcc-13" >> $GITHUB_ENV
          echo "CXX=g++-13" >> $GITHUB_ENV

      - name: Install Ninja and ccache (macOS)
        if: runner.os == 'macOS'
        run: brew install ninja ccache

      - name: Install Ninja (Windows)
        if: runner.os == 'Windows'
        run: choco install ninja -y

      - name: Set up MSVC environment (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: conan-${{ runner.os }}-${{ matrix.build_type }}-${{ hashFiles('conanfile.py', 'conandata.yml') }}
          restore-keys: |
            conan-${{ runner.os }}-${{ matrix.build_type }}-
            conan-${{ runner.os }}-

      - name: Cache ccache (Linux/macOS)
        if: runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ matrix.build_type }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ matrix.build_type }}-
            ccache-${{ runner.os }}-

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install "conan>=2.0,<3.0"

      - name: Enable ccache (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "CMAKE_C_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
          echo "CMAKE_CXX_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
          ccache --set-config=cache_dir=$HOME/.ccache
          ccache --set-config=max_size=2G
          ccache --set-config=compression=true
          ccache --zero-stats

      - name: Create Conan profile
        shell: bash
        run: |
          mkdir -p ~/.conan2/profiles
          cat > ~/.conan2/profiles/ci_profile << 'EOF'
          [settings]
          os=${{ runner.os == 'Linux' && 'Linux' || runner.os == 'macOS' && 'Macos' || 'Windows' }}
          arch=${{ runner.os == 'macOS' && 'armv8' || 'x86_64' }}
          compiler=${{ runner.os == 'Linux' && 'gcc' || runner.os == 'macOS' && 'apple-clang' || 'msvc' }}
          compiler.version=${{ runner.os == 'Linux' && '13' || runner.os == 'macOS' && '15' || '194' }}
          compiler.cppstd=23
          build_type=${{ matrix.build_type }}
          EOF
          if [ "${{ runner.os }}" == "Windows" ]; then
            echo "compiler.runtime=dynamic" >> ~/.conan2/profiles/ci_profile
            echo "compiler.runtime_type=${{ matrix.build_type }}" >> ~/.conan2/profiles/ci_profile
          elif [ "${{ runner.os }}" == "macOS" ]; then
            echo "compiler.libcxx=libc++" >> ~/.conan2/profiles/ci_profile
          else
            echo "compiler.libcxx=libstdc++11" >> ~/.conan2/profiles/ci_profile
          fi

      - name: Set LD_LIBRARY_PATH for GCC-13 (Linux)
        if: runner.os == 'Linux'
        run: echo "LD_LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/13" >> $GITHUB_ENV

      - name: Install dependencies via Conan
        shell: bash
        run: |
          conan install . \
            --profile:build=ci_profile \
            --profile:host=ci_profile \
            --build=missing \
            -o "&:build_tests=True" \
            --conf="tools.cmake.cmaketoolchain:generator=Ninja" \
            --conf="tools.system.package_manager:mode=install" \
            --conf="tools.system.package_manager:sudo=True"

      - name: Configure CMake
        shell: bash
        run: |
          PRESET=${{ matrix.build_type == 'Debug' && 'debug' || 'default' }}
          EXTRA_FLAGS=""
          if [[ -n "${CMAKE_C_COMPILER_LAUNCHER}" && -n "${CMAKE_CXX_COMPILER_LAUNCHER}" ]]; then
            EXTRA_FLAGS+=" -DCMAKE_C_COMPILER_LAUNCHER=${CMAKE_C_COMPILER_LAUNCHER} -DCMAKE_CXX_COMPILER_LAUNCHER=${CMAKE_CXX_COMPILER_LAUNCHER}"
          fi
          cmake --preset $PRESET -D HUMBLEENGINE_ENABLE_SANITIZERS=OFF ${EXTRA_FLAGS}
        if: runner.os != 'Windows'

      - name: Configure CMake (Windows)
        shell: pwsh
        run: |
          $preset = if ("${{ matrix.build_type }}" -eq "Debug") { "debug" } else { "default" }
          cmake --preset $preset -D HUMBLEENGINE_ENABLE_SANITIZERS=OFF
        if: runner.os == 'Windows'

      - name: Build project
        shell: bash
        run: |
          PRESET=${{ matrix.build_type == 'Debug' && 'debug' || 'default' }}
          cmake --build --preset $PRESET --parallel
        if: runner.os != 'Windows'

      - name: Build project (Windows)
        shell: pwsh
        run: |
          $preset = if ("${{ matrix.build_type }}" -eq "Debug") { "debug" } else { "default" }
          cmake --build --preset $preset --parallel
        if: runner.os == 'Windows'

      - name: Run tests
        shell: bash
        run: ctest --test-dir build/${{ matrix.build_type }} --output-on-failure --parallel
        if: runner.os != 'Windows'

      - name: Run tests (Windows)
        shell: pwsh
        run: |
          ctest --test-dir build/${{ matrix.build_type }} --output-on-failure --parallel
        if: runner.os == 'Windows'

      - name: ccache stats (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          which ccache && ccache -s || true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.build_type }}
          path: |
            build/${{ matrix.build_type }}/Testing/
            build/${{ matrix.build_type }}/**/test-results/
          retention-days: 14

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.os }}-${{ matrix.build_type }}
          path: |
            build/${{ matrix.build_type }}/CMakeFiles/*.log
            build/${{ matrix.build_type }}/**/*.log
            ~/.conan2/logs/
          retention-days: 14
